"""create monitoring time-series schema

Revision ID: 93389c6a776f
Revises: 
Create Date: 2026-03-30 10:27:43.113721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93389c6a776f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hostid', sa.BigInteger(), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('visible_name', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostid'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_hosts_id'), 'hosts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('itemid', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=True),
    sa.Column('units', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('item_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('clock', sa.DateTime(), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clock', 'item_history', ['clock'], unique=False)
    op.create_index('idx_item_clock', 'item_history', ['item_id', 'clock'], unique=False)
    op.create_index('idx_item_clock_desc', 'item_history', ['item_id', sa.literal_column('clock DESC')], unique=False)
    op.create_index(op.f('ix_item_history_clock'), 'item_history', ['clock'], unique=False)
    op.create_table('last_values',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('last_clock', sa.DateTime(), nullable=False),
    sa.Column('last_value_numeric', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_values')
    op.drop_index(op.f('ix_item_history_clock'), table_name='item_history')
    op.drop_index('idx_item_clock_desc', table_name='item_history')
    op.drop_index('idx_item_clock', table_name='item_history')
    op.drop_index('idx_clock', table_name='item_history')
    op.drop_table('item_history')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hosts_id'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
